import { 
  MIN_PAYMENT_AMOUNT,
  PROTOCOL_TREASURY,
  PROTOCOL_FEE_BPS,
  PAYNODE_ROUTER_ADDRESS,
  PAYNODE_ROUTER_ADDRESS_SANDBOX,
  BASE_USDC_ADDRESS,
  BASE_USDC_ADDRESS_SANDBOX,
  BASE_RPC_URLS,
  BASE_RPC_URLS_SANDBOX
} from '@paynodelabs/sdk-js';

export { MIN_PAYMENT_AMOUNT, PROTOCOL_TREASURY, PROTOCOL_FEE_BPS };

export const BASE_MAINNET_CONFIG = {
  chainId: 8453,
  rpcUrls: BASE_RPC_URLS,
  routerAddress: PAYNODE_ROUTER_ADDRESS,
  usdcAddress: BASE_USDC_ADDRESS,
  treasury: PROTOCOL_TREASURY
};

export const BASE_SEPOLIA_CONFIG = {
  chainId: 84532,
  rpcUrls: BASE_RPC_URLS_SANDBOX,
  routerAddress: PAYNODE_ROUTER_ADDRESS_SANDBOX,
  usdcAddress: BASE_USDC_ADDRESS_SANDBOX,
  treasury: PROTOCOL_TREASURY
};

export const getNetworkConfig = (isMainnet: boolean) => isMainnet ? BASE_MAINNET_CONFIG : BASE_SEPOLIA_CONFIG;
