/** Generated by meta/scripts/sync-config.py */
export const PROTOCOL_TREASURY = "0x598bF63F5449876efafa7b36b77Deb2070621C0E";
export const PROTOCOL_FEE_BPS = 100;
export const MIN_PAYMENT_AMOUNT = BigInt(1000);

export const BASE_MAINNET_CONFIG = {
  chainId: 8453,
  rpcUrls: ["https://mainnet.base.org", "https://base.meowrpc.com", "https://1rpc.io/base"],
  routerAddress: "0x4A73696ccF76E7381b044cB95127B3784369Ed63",
  usdcAddress: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  treasury: "0x598bF63F5449876efafa7b36b77Deb2070621C0E"
};

export const BASE_SEPOLIA_CONFIG = {
  chainId: 84532,
  rpcUrls: ["https://sepolia.base.org", "https://base-sepolia-rpc.publicnode.com"],
  routerAddress: "0x24cD8b68aaC209217ff5a6ef1Bf55a59f2c8Ca6F",
  usdcAddress: "0x65c088EfBDB0E03185Dbe8e258Ad0cf4Ab7946b0",
  treasury: "0x598bF63F5449876efafa7b36b77Deb2070621C0E"
};

export const getNetworkConfig = (isMainnet: boolean) => isMainnet ? BASE_MAINNET_CONFIG : BASE_SEPOLIA_CONFIG;
